// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  add: string;
  button: string;
  remove: string;
}
export const cssExports: CssExports;
export default cssExports;
