// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'close': string;
  'closeButton': string;
  'homeButton': string;
  'navItem': string;
  'navLink': string;
  'title': string;
  'titleButton': string;
}
export const cssExports: CssExports;
export default cssExports;
