// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  container: string;
  group: string;
  input: string;
}
export const cssExports: CssExports;
export default cssExports;
