// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  actions: string;
  button: string;
  buttonDanger: string;
  cell: string;
  container: string;
  editIcon: string;
  label: string;
  rowHeading: string;
}
export const cssExports: CssExports;
export default cssExports;
